// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Qv@;p79@e|(fGBFKaJ@[":
            case "mole":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 4 4 4 4 4 4 4 4 4 4 4 4 . . 
. 4 4 4 4 4 4 4 4 4 4 4 4 4 4 . 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 9 4 4 4 9 4 4 4 5 f 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
`;
            case "/LJ4HDC9/+6j@JGvC7#:":
            case "grid":return img`
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbb
bbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbb
bbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbb
bbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbb
bbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbb
bbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbb
bbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbb
bbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbb
bbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbb
bbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbb
bbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbb
bbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbb
bbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbb
bbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbb
bbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbb
bbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbb
bbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbb
bbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbb
bbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbb
bbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbb
bbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbfffbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbb
bbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbb
bbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbb
bbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbbbbfbbbbbbbbcccccccccccccccccccbbbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbbbbfbbbbbbbccccccccccccccccccccccbbbbbbfbbbbbbbbbbb
bbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbbbbfbbbbccccccccccccccccccccccccccccbbbfbbbbbbbbbbb
bbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbfbbccccccccccccccccccccccccccccccccbfbbbbbbbbbbb
bbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbbbbfbcccccccccccccccccccccccccccccccccbfbbbbbbbbbbb
bbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccccccfbbbbbbbbbbb
bbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbfccccccccccccccccccccccccccccccccccbbbbbbbbbbbb
bbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccccccccfbbbbbbbbbbbbb
bbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccccffbbbbbbbbbbbbb
bbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccccccccffbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbbbbbbbbbfcccccccccccccccccccccccccfbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccccccffbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccccccccccccccccffbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffff
fffffffffffff1fffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff1fffffffffffff1fffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff1ffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffff1fffffffffffffff1fffffff1fffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffff1fffff1ffffff
fffffffffffffffffffffffffffff1fffffffffffffff1ffffffffffffffffffffffffffff1ffffffffffff1fffffff1fffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
ffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffff1ffffffffffffffffffffff1fffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "Oag!`vsg+~Y,+WT2meT;":
            case "hammer":return img`
................................
................................
................................
................................
................................
................................
....................22..........
...................222..........
..................222...........
.................222............
................222.............
...............222..............
..............222...............
.............222................
............222.................
...........222..................
..........222...................
.........ff2....................
........fff.....................
.......fff......................
......fff.......................
.....fff........................
.....ff.........................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "hammerAnimation":
            case "anim2":return [img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.........ffffff2222222222222....
.........ffffff2222222222222....
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
......ff........................
......fff.......................
.......fff......................
........fff.....................
.........fff....................
..........ff2...................
...........222..................
............222.................
.............222................
..............222...............
...............222..............
................222.............
.................222............
..................222...........
...................222..........
....................222.........
.....................22.........
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`, img`
................................
................................
................................
................................
................................
......................22........
.....................222........
....................222.........
...................222..........
..................222...........
.................222............
................222.............
...............222..............
..............222...............
.............222................
............222.................
...........ff2..................
..........fff...................
.........fff....................
........fff.....................
.......fff......................
.......ff.......................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`];
            case "moleAnimation":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 4 4 4 4 4 4 4 4 4 4 4 4 . . 
. 4 4 4 4 4 4 4 4 4 4 4 4 4 4 . 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 9 4 4 4 9 4 4 4 5 f 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 4 4 4 4 4 4 4 4 4 4 4 4 . . 
. 4 4 4 4 4 4 4 4 4 4 4 4 4 4 . 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 9 4 4 4 9 4 4 4 5 f 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 4 4 4 4 4 4 4 4 4 4 4 4 . . 
. 4 4 4 4 4 4 4 4 4 4 4 4 4 4 . 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 9 4 4 4 9 4 4 4 5 f 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 4 4 4 4 4 4 4 4 4 4 4 4 . . 
. 4 4 4 4 4 4 4 4 4 4 4 4 4 4 . 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 9 4 4 4 9 4 4 4 5 f 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 4 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
